[package]
name = "dice-rust"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "dice_rust"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
rand = "0.9.2"
thiserror = "2.0.12"

[workspace]
members = [".", "ci"]
